# Generated by Django 5.1.4 on 2025-01-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('creator', 'Creator'), ('consumer', 'Consumer'), ('admin', 'Admin')], max_length=10),
        ),
    ]
