# Generated by Django 5.1.4 on 2025-01-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
